# Home Assistant Community Store (HACS) Repository Configuration
# https://hacs.xyz/docs/publish/start

name: "Hailo AI Terminal Add-on Repository"
description: "AI-powered terminal and resource monitor for Home Assistant with Hailo hardware acceleration"
render_readme: true
zip_release: false
filename: false
country: []
homeassistant: "2023.3.0"