name: "Add-on CI/CD"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: "ubuntu-latest"
    name: "Build Add-on"
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Build Add-on"
        uses: "home-assistant/builder@2023.09.0"
        with:
          args: |
            --target ./addons/hailo-terminal \
            --generic ${{ matrix.arch }}

  lint:
    runs-on: "ubuntu-latest"
    name: "Lint"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Lint Add-on"
        uses: "frenck/action-addon-linter@v2.15"
        with:
          path: "./addons/hailo-terminal"